title: "Um Sysadmin Cansado"
author: "Leonardo Amaral"
description: "Um blog cansado de um Sysadmin cansado <b style=\"color: #f45;\">&lt;3</b> by <b><a href=\"https://leleobhz.github.io\">https://leleobhz.github.io</a></b>"
permalink: /:title/
lang: "pt-BR"
excerpt_separator: "\n\n\n"

# Layout

sidebar: false               # show a sidebar instead of the usual header
show_excerpts: true          # show article excerpts on the home page
show_related: true          # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true             # always keep the site title visible

# Styling

dark_header: true           # always keep the header dark
minimal: false               # use simpler style
mathjax: true

# Menu

navigation:
  - {file: "index.html", icon: home}

external:                    # see http://fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/pqatsi"}
  - {title: Github, icon: github, url: "https://github.com/leleobhz"}
  - {title: RSS, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
